name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  geolocator: ^9.0.2
  http: ^1.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Inter Bold
      fonts:
        - asset: fonts/Inter-Bold.otf

    - family: Inter Light
      fonts:
        - asset: fonts/Inter-Light.otf

    - family: Ubuntu Light
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto.ttf